# Generated by Django 5.2.8 on 2025-11-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
