# Generated by Django 5.2.8 on 2025-11-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idor', '0002_remove_student_last_login_remove_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avg_mark',
            field=models.FloatField(),
        ),
    ]
